### ISSUE TITLE
Add MultiXML

### ISSUE THREAD

**Issue by sferik** [jamesarosen/ruby_interfaces#13]
MultiXML is a generic swappable back-end for XML parsing, inspired by MultiJSON.

It currently supports LibXML, Nokogiri, and REXML. MultiXML is already being used in the faraday_middleware gem and was featured on the Changelog (http://lg.gd/2n). Presumably, it will be bundled into more projects as awareness of the gem increases.

**Comment by jamesarosen** [comment]
Awesome! Will be incorporated soon.

**Comment by sferik** [comment]
FYI, 0.1.0 was just released, which adds support for LibXML and Nokogiri: http://github.com/sferik/multi_xml/commit/856bb17fce66601e0b3d3eb3b64dbeb25aed3bca

**Comment by jamesarosen** [comment]
Resolved in 17b7a9574988a4c281202254d863c216f8c7d328
